//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.pas.ha.org.hk/", ConfigurationName="HKSoap.PatientServiceSoap")]
    public interface PatientServiceSoap {
        
        // CODEGEN: Generating message contract since the operation searchHKPMIPatientByCaseNo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.pas.ha.org.hk/searchHKPMIPatientByCaseNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoResponse1 searchHKPMIPatientByCaseNo(Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oracle.com/weblogic/soap/workarea/")]
    public partial class WorkContextSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns {
            get {
                return this.xmlnsField;
            }
            set {
                this.xmlnsField = value;
                this.RaisePropertyChanged("Xmlns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string buildingField;
        
        private string districtCodeField;
        
        private string fullEnglishAddressField;
        
        private string record_idField;
        
        private string roomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string districtCode {
            get {
                return this.districtCodeField;
            }
            set {
                this.districtCodeField = value;
                this.RaisePropertyChanged("districtCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fullEnglishAddress {
            get {
                return this.fullEnglishAddressField;
            }
            set {
                this.fullEnglishAddressField = value;
                this.RaisePropertyChanged("fullEnglishAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string record_id {
            get {
                return this.record_idField;
            }
            set {
                this.record_idField = value;
                this.RaisePropertyChanged("record_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
                this.RaisePropertyChanged("room");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class patient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private address addressField;
        
        private string cCCode1Field;
        
        private string cCCode2Field;
        
        private string cCCode3Field;
        
        private string cCCode4Field;
        
        private string cCCode5Field;
        
        private string cCCode6Field;
        
        private string chineseNameField;
        
        private string confidentialFlagField;
        
        private string dOBField;
        
        private string exactDOBFlagField;
        
        private string hKIDField;
        
        private string hkicSymbolField;
        
        private string homePhoneField;
        
        private string keyField;
        
        private string lastPayCodeField;
        
        private string maritalStatusField;
        
        private string nameField;
        
        private string officePhoneField;
        
        private string raceField;
        
        private string sexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CCCode1 {
            get {
                return this.cCCode1Field;
            }
            set {
                this.cCCode1Field = value;
                this.RaisePropertyChanged("CCCode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CCCode2 {
            get {
                return this.cCCode2Field;
            }
            set {
                this.cCCode2Field = value;
                this.RaisePropertyChanged("CCCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CCCode3 {
            get {
                return this.cCCode3Field;
            }
            set {
                this.cCCode3Field = value;
                this.RaisePropertyChanged("CCCode3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CCCode4 {
            get {
                return this.cCCode4Field;
            }
            set {
                this.cCCode4Field = value;
                this.RaisePropertyChanged("CCCode4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CCCode5 {
            get {
                return this.cCCode5Field;
            }
            set {
                this.cCCode5Field = value;
                this.RaisePropertyChanged("CCCode5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CCCode6 {
            get {
                return this.cCCode6Field;
            }
            set {
                this.cCCode6Field = value;
                this.RaisePropertyChanged("CCCode6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string chineseName {
            get {
                return this.chineseNameField;
            }
            set {
                this.chineseNameField = value;
                this.RaisePropertyChanged("chineseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string confidentialFlag {
            get {
                return this.confidentialFlagField;
            }
            set {
                this.confidentialFlagField = value;
                this.RaisePropertyChanged("confidentialFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string exactDOBFlag {
            get {
                return this.exactDOBFlagField;
            }
            set {
                this.exactDOBFlagField = value;
                this.RaisePropertyChanged("exactDOBFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HKID {
            get {
                return this.hKIDField;
            }
            set {
                this.hKIDField = value;
                this.RaisePropertyChanged("HKID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string hkicSymbol {
            get {
                return this.hkicSymbolField;
            }
            set {
                this.hkicSymbolField = value;
                this.RaisePropertyChanged("hkicSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("homePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string lastPayCode {
            get {
                return this.lastPayCodeField;
            }
            set {
                this.lastPayCodeField = value;
                this.RaisePropertyChanged("lastPayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("maritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string officePhone {
            get {
                return this.officePhoneField;
            }
            set {
                this.officePhoneField = value;
                this.RaisePropertyChanged("officePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
                this.RaisePropertyChanged("race");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("sex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class @case : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string admissionDatetimeField;
        
        private string bedNoField;
        
        private string hospitalCodeField;
        
        private string numberField;
        
        private string patientTypeField;
        
        private string sourceCodeField;
        
        private string sourceIndicatorField;
        
        private string specialtyField;
        
        private string typeField;
        
        private string wardClassField;
        
        private string wardCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string admissionDatetime {
            get {
                return this.admissionDatetimeField;
            }
            set {
                this.admissionDatetimeField = value;
                this.RaisePropertyChanged("admissionDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bedNo {
            get {
                return this.bedNoField;
            }
            set {
                this.bedNoField = value;
                this.RaisePropertyChanged("bedNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hospitalCode {
            get {
                return this.hospitalCodeField;
            }
            set {
                this.hospitalCodeField = value;
                this.RaisePropertyChanged("hospitalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string patientType {
            get {
                return this.patientTypeField;
            }
            set {
                this.patientTypeField = value;
                this.RaisePropertyChanged("patientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("sourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sourceIndicator {
            get {
                return this.sourceIndicatorField;
            }
            set {
                this.sourceIndicatorField = value;
                this.RaisePropertyChanged("sourceIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string specialty {
            get {
                return this.specialtyField;
            }
            set {
                this.specialtyField = value;
                this.RaisePropertyChanged("specialty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string wardClass {
            get {
                return this.wardClassField;
            }
            set {
                this.wardClassField = value;
                this.RaisePropertyChanged("wardClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string wardCode {
            get {
                return this.wardCodeField;
            }
            set {
                this.wardCodeField = value;
                this.RaisePropertyChanged("wardCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatientDemoEnquiry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private @case[] caseListField;
        
        private patient patientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public @case[] caseList {
            get {
                return this.caseListField;
            }
            set {
                this.caseListField = value;
                this.RaisePropertyChanged("caseList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public patient patient {
            get {
                return this.patientField;
            }
            set {
                this.patientField = value;
                this.RaisePropertyChanged("patient");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.pas.ha.org.hk/")]
    public partial class SearchHKPMIPatientByCaseNoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PatientDemoEnquiry patientDemoEnquiryResultField;
        
        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="", Order=0)]
        public PatientDemoEnquiry PatientDemoEnquiryResult {
            get {
                return this.patientDemoEnquiryResultField;
            }
            set {
                this.patientDemoEnquiryResultField = value;
                this.RaisePropertyChanged("PatientDemoEnquiryResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns {
            get {
                return this.xmlnsField;
            }
            set {
                this.xmlnsField = value;
                this.RaisePropertyChanged("Xmlns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.pas.ha.org.hk/")]
    public partial class SearchHKPMIPatientByCaseNo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hospitalCodeField;
        
        private string caseNoField;
        
        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="", Order=0)]
        public string hospitalCode {
            get {
                return this.hospitalCodeField;
            }
            set {
                this.hospitalCodeField = value;
                this.RaisePropertyChanged("hospitalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="", Order=1)]
        public string caseNo {
            get {
                return this.caseNoField;
            }
            set {
                this.caseNoField = value;
                this.RaisePropertyChanged("caseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces Xmlns {
            get {
                return this.xmlnsField;
            }
            set {
                this.xmlnsField = value;
                this.RaisePropertyChanged("Xmlns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchHKPMIPatientByCaseNoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://oracle.com/weblogic/soap/workarea/")]
        public Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.WorkContextSoapHeader WorkContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.pas.ha.org.hk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNo searchHKPMIPatientByCaseNo;
        
        public searchHKPMIPatientByCaseNoRequest() {
        }
        
        public searchHKPMIPatientByCaseNoRequest(Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.WorkContextSoapHeader WorkContext, Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNo searchHKPMIPatientByCaseNo) {
            this.WorkContext = WorkContext;
            this.searchHKPMIPatientByCaseNo = searchHKPMIPatientByCaseNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchHKPMIPatientByCaseNoResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://oracle.com/weblogic/soap/workarea/")]
        public Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.WorkContextSoapHeader WorkContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.pas.ha.org.hk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNoResponse searchHKPMIPatientByCaseNoResponse;
        
        public searchHKPMIPatientByCaseNoResponse1() {
        }
        
        public searchHKPMIPatientByCaseNoResponse1(Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.WorkContextSoapHeader WorkContext, Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNoResponse searchHKPMIPatientByCaseNoResponse) {
            this.WorkContext = WorkContext;
            this.searchHKPMIPatientByCaseNoResponse = searchHKPMIPatientByCaseNoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientServiceSoapChannel : Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.PatientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientServiceSoapClient : System.ServiceModel.ClientBase<Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.PatientServiceSoap>, Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.PatientServiceSoap {
        
        public PatientServiceSoapClient() {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoResponse1 Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.PatientServiceSoap.searchHKPMIPatientByCaseNo(Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoRequest request) {
            return base.Channel.searchHKPMIPatientByCaseNo(request);
        }
        
        public Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNoResponse searchHKPMIPatientByCaseNo(ref Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.WorkContextSoapHeader WorkContext, Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.SearchHKPMIPatientByCaseNo searchHKPMIPatientByCaseNo1) {
            Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoRequest inValue = new Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoRequest();
            inValue.WorkContext = WorkContext;
            inValue.searchHKPMIPatientByCaseNo = searchHKPMIPatientByCaseNo1;
            Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.searchHKPMIPatientByCaseNoResponse1 retVal = ((Demo.HL7MessageParser.ServiceSimulator.Test.HKSoap.PatientServiceSoap)(this)).searchHKPMIPatientByCaseNo(inValue);
            WorkContext = retVal.WorkContext;
            return retVal.searchHKPMIPatientByCaseNoResponse;
        }
    }
}
